services:
  server-build:
    build:
      context: .
      no_cache: true
    profiles: [build]
    depends_on:
      - database
    ports:
      - 3000:3000

  server:
    image: localhost/next:latest
    profiles: [ready]
    depends_on:
      - database
    ports:
      - 3000:3000

  database:
    image: "postgres:17-alpine"
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer:5-standalone
    ports:
      - 18080:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database

  mail:
    image: maildev/maildev
    ports:
      - 11080:1080

  ai:
    image: ollama/ollama
    profiles: [ai]
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
