services:
  database:
    image: "postgres:17-alpine"
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@example.com
      PGADMIN_DEFAULT_PASSWORD: password

  adminer:
    image: adminer:5-standalone
    ports:
      - 18080:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database

  mail:
    image: maildev/maildev
    ports:
      - 11025:1025
      - 11080:1080

  ai:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama

  s3:
    image: minio/minio
    ports:
      - 19000:9000
      - 19001:9001
    volumes:
      - s3:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

volumes:
  ollama:
  s3:
