INSERT INTO public."ingredient" ("id", "name", "quantity", "price", "avaliableInComposer", "category", "icon", "image", "zIndex") VALUES
(1, 'Sos pomidorowy', 99999, 0, '1', 'sauce', '/composer/toppings/sauce-tomato.png', '/composer/toppings/sauce-tomato.png', 10),
(2, 'Sos biały', 9999, 0, '1', 'sauce', '/composer/toppings/sauce-cream.png', '/composer/toppings/sauce-cream.png', 10),
(3, 'Sos BBQ', 999, 2, '1', 'sauce', '/composer/toppings/sauce-bbq.png', '/composer/toppings/sauce-bbq.png', 10),
(4, 'Sos Sriracha', 99, 2, '1', 'sauce', '/composer/toppings/sauce-sriracha.png', '/composer/toppings/sauce-sriracha.png', 10),
(5, 'Szynka', 9, 5, '1', 'meat', '/composer/icons/szynka.png', '/composer/toppings/szynka.png', 30),
(6, 'Salami Pepperoni', 9, 6, '1', 'meat', '/composer/icons/salami.png', '/composer/toppings/salami.png', 30),
(7, 'Kurczak Grillowany', 9, 6, '1', 'meat', '/composer/icons/kurczak.png', '/composer/toppings/kurczak.png', 30),
(8, 'Mozzarella', 9, 5, '1', 'cheese', '/composer/icons/mozzarella.png', '/composer/toppings/mozzarella.png', 20),
(9, 'Feta', 9, 5, '1', 'cheese', '/composer/icons/feta.png', '/composer/toppings/feta.png', 50),
(10, 'Gorgonzola', 9, 6, '1', 'cheese', '/composer/icons/gorgonzola.png', '/composer/toppings/gorgonzola.png', 50),
(11, 'Parmezan', 5, 5, '1', 'cheese', '/composer/icons/parmezan.png', '/composer/toppings/parmezan.png', 55),
(12, 'Cebula', 4, 2, '1', 'vegetable', '/composer/icons/cebula.png', '/composer/toppings/cebula.png', 25),
(13, 'Kukurydza', 2, 2, '1', 'vegetable', '/composer/icons/kukurydza.png', '/composer/toppings/kukurydza.png', 25),
(14, 'Papryka', 3, 3, '1', 'vegetable', '/composer/icons/papryka.png', '/composer/toppings/papryka.png', 25),
(15, 'Pieczarki', 3, 3, '1', 'vegetable', '/composer/icons/pieczarki.png', '/composer/toppings/pieczarki.png', 25),
(16, 'Pomidorki koktajlowe', 3, 3, '1', 'vegetable', '/composer/icons/pomidorki.png', '/composer/toppings/pomidorki.png', 45),
(17, 'Oliwki', 4, 4, '1', 'vegetable', '/composer/icons/oliwki.png', '/composer/toppings/oliwki.png', 40),
(18, 'Jalapeno', 4, 4, '1', 'vegetable', '/composer/icons/jalapeno.png', '/composer/toppings/jalapeno.png', 40),
(19, 'Świeża Bazylia', 3, 3, '1', 'vegetable', '/composer/icons/bazylia.png', '/composer/toppings/bazylia.png', 60),
(20, 'Rukola', 4, 4, '1', 'vegetable', '/composer/icons/rukola.png', '/composer/toppings/rukola.png', 60),
(21, 'Ananas', 3, 3, '1', 'vegetable', '/composer/icons/ananas.png', '/composer/toppings/ananas.png', 30),
(22, 'Oregano', 1, 0, '0', 'other', NULL, NULL, NULL);